name: Build EXE

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      
      - name: Debug file structure
        run: Get-ChildItem -Path . -Recurse
      
      - name: Build Executable
        working-directory: ./src
        run: |
          pyinstaller --noconfirm --onefile --name "DNA_Chart_App" --windowed main.py
      
      - name: Upload EXE as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DNA_Chart_App
          path: src/dist/DNA_Chart_App.exe

      - name: Create GitHub Release (on tag push)
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: "src/dist/DNA_Chart_App.exe"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          name: "Release ${{ github.ref }}"
          body: "Automatic build of DNA_Chart_App.exe"
